# Generated by Django 4.1 on 2024-02-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0011_alter_stock_latestupdatetime"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="price",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="trade",
            name="stockinfo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.stockprice",
            ),
        ),
    ]
