# Generated by Django 5.0.2 on 2024-03-07 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('user', '0002_trade_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='stockinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock'),
        ),
    ]
