# Generated by Django 4.1 on 2024-02-13 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0011_alter_stock_latestupdatetime"),
        ("user", "0002_remove_trade_price_remove_trade_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="stockinfo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.stockprice",
            ),
        ),
    ]
