# Generated by Django 5.0.2 on 2024-03-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritestock',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
