# Generated by Django 5.0.2 on 2024-03-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_owner_favoritestock_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
