# Generated by Django 5.0.2 on 2024-03-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_trade_stockinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritestock',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='stockinfo',
        ),
        migrations.AddField(
            model_name='favoritestock',
            name='symbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='symbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
