# Generated by Django 5.0.2 on 2024-03-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_favoritestock_stock_remove_trade_stockinfo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritestock',
            old_name='symbol',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='symbol',
            new_name='stockinfo',
        ),
    ]
