# Generated by Django 5.0.2 on 2024-03-07 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('companytype', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('iconurl', models.URLField(blank=True, max_length=1200, null=True)),
                ('latestupdatetime', models.BigIntegerField(blank=True, null=True)),
                ('latestopenprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latestcloseprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latesthighprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latestlowprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('openprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('closeprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('highprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lowprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
    ]
