# Generated by Django 5.0.2 on 2024-02-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='latestupdatetime',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
