# Generated by Django 4.1 on 2024-02-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="companytype",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="homepage",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="iconurl",
            field=models.URLField(blank=True, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="latestprice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="latestuptatetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="location",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
