# Generated by Django 4.1 on 2024-02-11 01:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_stock_companytype_stock_description_stock_homepage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="latestuptatetime",
            new_name="latestupdatetime",
        ),
    ]
