# Generated by Django 4.1 on 2024-02-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0003_rename_latestuptatetime_stock_latestupdatetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockprice",
            name="price",
        ),
        migrations.RemoveField(
            model_name="stockprice",
            name="volume",
        ),
        migrations.AddField(
            model_name="stockprice",
            name="closeprice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockprice",
            name="highprice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockprice",
            name="lowprice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockprice",
            name="openprice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockprice",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
