# Generated by Django 4.1 on 2024-02-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0004_remove_stockprice_price_remove_stockprice_volume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockprice",
            name="timestamp",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
