# Generated by Django 4.1 on 2024-02-11 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0006_alter_stockprice_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockprice",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.stock",
            ),
        ),
    ]
