# Generated by Django 4.1 on 2024-02-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0007_alter_stockprice_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="companytype",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="symbol",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
