# Generated by Django 4.1 on 2024-02-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0008_alter_stock_companytype_alter_stock_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="latestprice",
            new_name="latestcloseprice",
        ),
        migrations.AddField(
            model_name="stock",
            name="latestopenprice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="latestupdatetime",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
