# Generated by Django 4.1 on 2024-02-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0009_rename_latestprice_stock_latestcloseprice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="latesthighprice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="latestlowprice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="latestupdatetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
