# Generated by Django 4.1 on 2024-02-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0010_stock_latesthighprice_stock_latestlowprice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="latestupdatetime",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
